### ISSUE TITLE
add i18n

### ISSUE THREAD

**Issue by Ks89** [Ks89/angular-webpack-skeleton#58]

**Comment by ltoshev** [comment]
Hi

I have an old NG1.5 project based on ng-translate library. I am trying to rewrite that project into your skeleton. Can you suggest what to use for replacement for ng-translate so I can use same translation files which are quite big and of course user same approach as 'transl-key' | translate

**Comment by Ks89** [comment]
Hi. I'm sorry but I don't know how to help you.
I stopped the implementation of this feature.

**Comment by Ks89** [comment]
Project officially deprecated and replaced by https://github.com/Ks89/angular-cli-skeleton

All issues will be closed

I hope to see all of you to use my new project based on angular-cli (recommended today)
