### ISSUE TITLE
How to inject lodash to use in component/service?

### ISSUE THREAD

**Issue by ltoshev** [Ks89/angular-webpack-skeleton#61]
Hi

I am trying to use lodash, it is included in the skeleton.

I tried this in a service:

constructor(private lodash: _.LoDashStatic) {} the injector fails to inject it.

I have tried also to use it just as a varibale:

private lodash: _.LoDashStatic;

Then it is undefined.

Can you suggest how is the proper way to initialize this so I can use it in a service or a component?

**Comment by Ks89** [comment]
Hi. Lodash is a pure js library, so it isn't an injectable service.

Try with:
import * as _ from 'lodash'

**Comment by ltoshev** [comment]
Thanks. Closing
