### ISSUE TITLE
How is the proper way to include scss files?

### ISSUE THREAD

**Issue by ltoshev** [Ks89/angular-webpack-skeleton#62]
Hi 

I have an old project with lots of scss. I have moved them under 

feang4\src\styles

but I get lots of build errors for impossible to include resources like missing images and fonts.

Like:

 using description file: C:\123\feang4\package.json (relative path: ./src/styles/img/loader.gif)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\123\feang4\src\styles\img\loader.gif doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\123\feang4\src\styles\img\loader.gif.ts doesn't exist
      .js

How is the proper way to refer to resources from the styles dir?

I guess the resources need to go into C:\123\feang4\assets

I copied /img and /fonts under /assets.

How is the proper way to locate those from /src/styles/some.scss file?

**Comment by ltoshev** [comment]
Also in prod I want the scss to get compiled into one css bundle to get included as one css file. Currnetly in dev it seems to include the css as <style> tags somehow dynamically.

**Comment by ltoshev** [comment]
Third question: how to tell the build to exclude looking for this asset in url(image-triangle($select-arrow-color))
it tries to look for a file 'image-triangle(' and does not find it of course since it is a mixin.

**Comment by Ks89** [comment]
> How is the proper way to locate those from /src/styles/some.scss file?

I never tried to do this. At the moment I cannot help you.

> Currnetly in dev it seems to include the css as <style> tags somehow dynamically.

Did you check if it is happen also in prod?


>  how to tell the build to exclude looking for this asset in url(image-triangle($select-arrow-color))

I don't understand this question.

**Comment by Ks89** [comment]
Project officially deprecated and replaced by https://github.com/Ks89/angular-cli-skeleton

All issues will be closed

I hope to see all of you to use my new project based on angular-cli (recommended today)
